version: '3'
services:
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: chess
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  springboot-app:
    build:
      context: ./backend/api
      dockerfile: Dockerfile.txt
    ports:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/chess
    depends_on:
      mysql:
        condition: service_healthy
    command: ["java", "-jar", "app.jar"]

  frontend:
    image: nginx:alpine
    volumes:
      - ./Frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5000:5000" 
    depends_on:
      - springboot-app